### ISSUE TITLE
Requête directement le fichier ICS?

### ISSUE THREAD

**Issue by ghost** [Victor-Loos/Aurion-Planning_to_ICS#1]
Salut ! Je suis en train d'essayer de faire à peu près la même chose que toi mais je galère : 
En regardant vite fait ton code je me suis demandé pourquoi tu ne fais pas la requête directement du fichier ICS? Lorsque tu cliques sur "télécharger" sur le site c'est aussi une requête POST qui est envoyée? Plutôt que de faire le parsing du fichier "manuellement". 

Bon ceci dit j'ai échoué à le faire, mais je pose la question au cas où tu aurais des pistes..

**Comment by Victor-Loos** [comment]
Salut.
Qu'est-ce que tu veux dire par lorsque tu cliques sur "télécharger" ? 

Le serveur nous empêche de récupérer les données du planning tant qu'on n'a pas chargé la page et MainMenuPage (le menu à gauche). Donc, on ne peut pas faire directement la requête.

**Comment by ghost** [comment]
Quand sur le site tu vas dans "Mon emploi du temps" -> le petit bouton qui sert à télécharger directement le planning en fichier .ics (en bas de la page)

Finalement je viens de réussir ! En imitant la requête qui se produit quand on clique sur le bouton télécharger, on peut directement obtenir le fichier.
Juste pour info la requête POST envoyée pour recevoir c'est ça : 
`form:form
form:offsetFuseauNavigateur:-3600000
form:j_idt236_input:44239
javax.faces.ViewState: <ViewState>
form:j_idt120:form:j_idt120`

Après comme tu l'as dit, le serveur empêche de récupérer tout ça directement, donc il faut faire croire au serveur que tu es arrivée sur la page, mais tu sais ça mieux que moi!

Merci!

**Comment by Victor-Loos** [comment]
Enfaite, tu parles de [PyAurion](https://github.com/Victor-Loos/PyAurion).

**Comment by ghost** [comment]
Non, dans ce projet (Aurion-planning_to_ICS) tu fais : 
Requête LogIn, Requête GETMainPage, Requête PostMainPage, Requête GETPlanning,Requête PostPlanning qui te donne une réponse pas au format .ICS.

Ma question/remarque était qu'en faisant une requête POST de plus sur planning, tu pouvais directement obtenir le fichier .ics, sans avoir à faire le parsing.

**Comment by Victor-Loos** [comment]
D'accord, j'ai compris, le site que tu utilises propose un bouton téléchargé qui effectue la requête adaptée pour recevoir un fichier aux formats ics ? (bouton qui n'est pas présent chez moi) 
Effectivement, c'est plus propre, bravo. Il faudrait que je regarde pour améliorer ça.
